on:
  push:
    branches:
      - master

jobs:
    release:
        runs-on: ubuntu-24.04
        permissions:
            contents: write
            issues: write
            packages: write
            pull-requests: write
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Semantic Release - tags
            id: semantic-release-tags
            uses: cycjimmy/semantic-release-action@v4
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              dry_run: true
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
            if: steps.semantic-release-tags.outputs.new_release_published
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
            id: qemu
            with:
              platforms: linux/amd64,linux/arm64
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Build and push
            uses: docker/build-push-action@v6
            with:
              push: true
              platforms: ${{ steps.qemu.outputs.platforms }}
              tags: |
                tedatech/pem-to-jwk:${{ steps.semantic-release-tags.outputs.new_release_version }}
                tedatech/pem-to-jwk:latest
              cache-from: type=gha
              cache-to: type=gha,mode=max
          - name: Semantic Release - release
            uses: cycjimmy/semantic-release-action@v4
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
